name: chat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  firebase_storage: ^12.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Social
      fonts:
        - asset: lib/core/assets/fonts/Social.ttf

